### ISSUE TITLE
Python version pinning

### ISSUE THREAD

**Issue by SultanOrazbayev** [coiled/coiled-runtime#121]
If I installed environment with the environment below (python is not pinned)

```yaml
name: test_coiled
channels:
- conda-forge
dependencies:
- python
- coiled-runtime=0.0.3
```

Then python 3.10 is installed on my machine (MacOS). However, later coiled asks for python 3.9 version.

Steps to reproduce:
- save the above yaml as environment.yml
```shell
conda env create -f environment.yml
conda activate test_coiled
python --version
```

The above prints `3.10.4`.
