### ISSUE TITLE
Automation of benchmark comparison

### ISSUE THREAD

**Issue by fjetter** [coiled/coiled-runtime#292]
## Requirements
- Be able to compare two distinct git handles (commit, branch, etc.) of dask/dask and/or dask/distributed; needs to target forks
- It is fine if it is merely possible to use a commit OR a branch OR a PR etc. instead of generic git refs
- Tests are used from the current commit / PR of the coiled-runtime
- Initial iteration must be extendable to compare N commits
- One or many CI job(s) is spawned that runs *all* available benchmarks and collects a summary
- The CI job collects all data that is also collected by the ordinary benchmark tests
- The CI job produces a summary / report comparing these single point numbers

## Nice to haves
- Varying config options
- Select a subset of the benchmarks to run
- Varying environment 
- Varying test code for different git handles (if a prototype change breaks an API, for example)
- We also want to collect memory sampling, performance reports, etc.

**Comment by crusaderky** [comment]
I went through the codebase. @jrbourbeau @ncclementi @ian-r-rose please correct me if I say something wrong or impossible.

The `Tests` github action does the following:
1. build the `latest` conda package for `coiled-runtime`
2. create coiled software environments for `latest`, `0.1.0`, and `0.0.4`, in cartesian product with different versions of python
3. run the full battery of tests against the coiled environments created at step 2
4. collect and compare results
5. destroy coiled software environments

If that's the case, my plan is fairly straightforward:

1. Create additional software environments
2. Create a new static HTML report to compare whatever was run in the battery of tests

Sample workflow
-----------------------
I want to test https://github.com/dask/distributed/pull/6614.

I create a new branch of coiled-runtime, in my own fork: `crusaderky/coiled-runtime/AB_6614`

In the new branch, I create the following files. Each file is a bunch of ``kwargs`` to `coiled.create_software_environment`:

#### AB_parameters/6614_before.yaml
```yaml
conda:
    - python=3.9
    - coiled-runtime=0.1.0
pip:
    - dask==2022.8.1
    - git+https://github.com/dask/distributed@f07f384eb0b8b6bad7518e8535e42fdba106ed4b
```

#### AB_parameters/6614_inf.yaml
```yaml
conda:
    - python=3.9
    - coiled-runtime=0.1.0
pip:
    - dask==2022.8.1
    - git+https://github.com/dask/distributed@dd81b424971e81616e1a52fa09ce4698a5002d41
```

#### AB_parameters/6614_12.yaml
```yaml
conda:
    - python=3.9
    - coiled-runtime=0.1.0
pip:
    - dask==2022.8.1
    - git+https://github.com/dask/distributed@dd81b424971e81616e1a52fa09ce4698a5002d41
environ:
    DASK_DISTRIBUTED__SCHEDULER__WORKER_SATURATION: "1.2"
```

##### Notes
- I could have used the nightly build of coiled-runtime instead
- I did not install dask 2022.8.1 using conda, because it would have conflicted with coiled-runtime=0.1.0. However, using pip allows you to bypass the constraints imposed by the conda recipe.
- I could have added a PR that hasn't been merged yet by simply creating a branch on my fork `https://github.com/crusaderky/distributed`

I then have to update `.github/workflows/tests.yaml`:
- In the (not yet existing) section "additional_environments", I change

```yaml
matrix:
  AB_environments: []
```
to

```yaml
matrix:
  AB_environments:
    - 6614_before
    - 6614_inf
    - 6614_12
```

- In the ``benchmarks``, ``runtime``, and ``stability`` sections, I update the matrix to whatever I'm interested in:
e.g. from
```yaml
  benchmarks:
    ...
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
        runtime-version: ["latest", "0.0.4", "0.1.0"]
```
to
```yaml
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9"]
        runtime-version: [AB_6614_before, AB_6614_inf, AB_6614_12]
``` 
**Note**: I would love to not need to touch `tests.yaml` and instead automatically generate those lists from a file. To my knowledge it's not possible but I will investigate.


Finally, I submit a PR named ``[DNM] A/B testing: distributed#6614`` and read the report out of the PR's artifacts.
When I'm done I close the PR without merging.

The static report will show side by side the time, peak memory, and average memory for each test from each test suite that has run and has the measure.

Further improvements, out of scope for this ticket:


# Requirements
All requirements in the OP are satisfied.

# Nice to haves
- Varying config options
Yep!
- Select a subset of the benchmarks to run
You can completely disable  ``benchmarks``, ``runtime``, or ``stability``. You can additionally cherry-pick tests by tampering with the lines in `tests.yaml` that call pytest.
- Varying environment
Yep!
- Varying test code for different git handles (if a prototype change breaks an API, for example)
Yep!
- We also want to collect memory sampling, performance reports, etc.
MemorySampler timeseries are definitely a possibility for a future iteration but are out of scope for now.
- Automatically highlight major changes
Out of scope for now; something straightforward to implement in the future
