### ISSUE TITLE
Configure number of workers and instance types in A/B tests

### ISSUE THREAD

**Issue by crusaderky** [coiled/coiled-runtime#483]
At the moment, all of our tests use hardcoded number of VMs and instance types - 10 x m6i.large for all tests that use the `small_client` fixture.

This leaves us blind to three major use cases:
- workers with more than 2 threads
- clusters with 20+ workers - this triggers completely different code paths in the scheduler
- clusters with many workers (100~10,000) - this can highlight problems with big-O complexity in the scheduler algorithms.

# Proposed design
It would be extremely costly to enable the above in the nightly tests, so I propose to add a switch to A/B tests and trigger them as needed.

Require new config files `AB_environments/AB_<name>.cluster.yaml`, with the following config:
```yaml
# These are arbitrary kwargs to coiled.Cluster

# For all tests using the small_client fixture
small_cluster:
  n_workers: 10
  worker_vm_types: [m6i.large]  # 2CPU, 8GiB
  scheduler_vm_types: [m6i.xlarge]

# For test_parquet.py
parquet_cluster:
  n_workers: 15
  worker_vm_types: [m5.xlarge]  # 4 CPU, 16 GiB
  scheduler_vm_types: [m5.xlarge]
```

and have them reach the respective fixtures.
Note that the above will not impact special tests which create their own clusters, e.g. test_spill.py.

Review all tests to verify that the test workload scales with the total amount of CPUs or memory in the cluster, so that you get a meaningful workload on a 10 workers cluster as well as on a 200 workers one.

Review which tests hit the spill threshold and, 
  - if spilling isn't an integral part of the test, make sure the test data is sized so that spilling is consistently avoided across various cluster sizes and threads per worker
  - (harder) if spilling IS an integral part of the test (read: shuffle), make sure the test data is sized so that spilling is consistently hit in roughly the same proportion

Note that, even with the review in dataset scaling above, it is expected that testing e.g. a 20-threads cluster vs. a 40-threads cluster is going to be comparing apples and oranges - namely for all tests that implement an algorithm that doesn't scale linearly with the number of chunks. However it will be very interesting to compare eg. how  a 10 workers, 2 threads-per-worker cluster compares to a 5 workers, 4 threads-per-worker one.
