### ISSUE TITLE
A nicer UX for A/B test recipes

### ISSUE THREAD

**Issue by crusaderky** [coiled/coiled-runtime#758]
Downstream of #732 and #757, it is no longer possible to have nice compact A/B environments that look like this:
```yaml
channels:
  - conda-forge
dependencies:
  - python=3.9
  - coiled-runtime=0.2.1
  - pip:
    - dask==2023.3.2
    - git+https://github.com/dask/distributed@54941387cb58b279a63dcb556ae6448789860118
```

Instead, we now have every single package explicitly listed in the environment files. This is extremely error-prone, as it makes it very hard to notice differences between environments, thus introducing unknown variables in the A/B test.

# Proposed design
Use some sort of tools to merge conda environment files, and use the coiled-runtime latest as a base + just the "diff" in AB_environments.

The tool must have the following features:
- must be able to move a package from conda to pip (if a package is added to pip in the diff it *must* be removed from conda)
- must be able to completely remove packages

@jrbourbeau you mentioned that you saw a tool like this in the wild?
